.SILENT:

build:
	gcc -o remote_commands remote_commands.c

run:
	gcc -o remote_commands remote_commands.c && ./remote_commands 8080

help:
	echo "build - build the app via gcc"
	echo "run - start app with default 8080 port"
